/* Dossiê de conteúdo — o que saber, e em que profundidade.
   Derivado do Anexo V do edital cruzado com a frequência real nas provas 2023.2–2026.2.

   tier  nucleo  → cai em toda prova (ou quase). Saber no automático, com detalhe.
         orbita  → cai em ~metade das provas. Saber bem, sem aprofundar.
         cauda   → está no Anexo V, mas é raro. Saber só o bastante para reconhecer
                   e eliminar alternativa. NUNCA gastar sessão inteira nisso.

   Formato: {area, tier, topico, freq, saber[], armadilha, fogo}
     saber     — o conteúdo exato, no nível exigido. Aceita <code> e <b>.
     armadilha — o erro que o IFSC explora nesse tópico.
     fogo      — teste de Feynman: se não explicar isso em voz alta, não sabe.        */
window.DOMINIO = [

/* ========================= MATEMÁTICA ========================= */
{area:"mat",tier:"nucleo",topico:"Área, perímetro e volume em contexto",freq:"~2 por prova — apareceu nas 7 provas analisadas",
 saber:["Retângulo <code>A=b·h</code>, triângulo <code>A=b·h/2</code>, círculo <code>A=πr²</code> e <code>C=2πr</code>, trapézio <code>A=(B+b)·h/2</code>.",
  "Volume de prisma/cilindro é sempre <b>área da base × altura</b>. Cilindro: <code>V=πr²h</code>.",
  "<code>1 m³ = 1000 L</code> e <code>1 dm³ = 1 L</code>. A prova adora pedir litros a partir de metros.",
  "Área composta: recortar a figura em retângulos e triângulos, somar. É assim que caem planta de apartamento e campo de futebol.",
  "Perímetro é contorno (cerca, rodapé, moldura); área é superfície (piso, tinta, grama). Ler qual dos dois o enunciado quer."],
 armadilha:"Dar o diâmetro e você usar como raio. E trocar unidade no meio: medida em cm, resposta pedida em m — área divide por 10.000, volume por 1.000.000.",
 fogo:"Por que a área quadruplica quando eu dobro o lado, mas o perímetro só dobra?"},

{area:"mat",tier:"nucleo",topico:"Porcentagem, desconto e acréscimo",freq:"~1 por prova, em todas",
 saber:["Desconto de 15% = multiplicar por <code>0,85</code>. Aumento de 15% = multiplicar por <code>1,15</code>. Sempre em um passo só.",
  "Descontos sucessivos <b>não somam</b>: 20% e depois 10% = <code>0,8 × 0,9 = 0,72</code> → 28% de desconto, não 30%.",
  "Achar a porcentagem: <code>parte / todo</code>, e depois ×100.",
  "Voltar ao preço original: se R$ 85 já tem 15% off, o original é <code>85 ÷ 0,85</code> — divide, não soma 15%.",
  "À vista × parcelado: calcular o total das parcelas e comparar com o preço à vista. A diferença é o custo do crédito."],
 armadilha:"Aumentar 20% e depois baixar 20% não volta ao começo — dá 0,96 do valor inicial, você perdeu 4%.",
 fogo:"Um produto subiu 25% e depois caiu 20%. Voltou ao preço original? Por quê?"},

{area:"mat",tier:"nucleo",topico:"Razão, proporção e regra de três",freq:"1 a 2 por prova, em todas",
 saber:["Montar a proporção escrevendo as unidades: se em cima tem 'reais', em cima do outro lado também tem 'reais'.",
  "Diretamente proporcional (mais operários, mais serviço) → multiplica cruzado normal.",
  "Inversamente proporcional (mais operários, <b>menos</b> tempo) → inverte uma das razões antes de cruzar.",
  "Escala é razão: <code>1:50.000</code> significa 1 cm no papel = 50.000 cm reais = 500 m.",
  "Divisão proporcional: repartir 120 na razão 2:3 → 5 partes de 24 → 48 e 72."],
 armadilha:"Aplicar regra de três direta numa situação inversa. Teste sempre: se eu aumento A, B aumenta ou diminui?",
 fogo:"Quando a regra de três é inversa? Dê um exemplo do dia a dia e explique por quê."},

{area:"mat",tier:"nucleo",topico:"Leitura de gráfico e tabela",freq:"1 a 2 por prova, em todas",
 saber:["Antes de olhar o desenho, ler: título, o que está no eixo x, o que está no eixo y e <b>a unidade</b>.",
  "Variação absoluta (quanto subiu) é diferente de variação relativa (quantos % subiu). O enunciado sempre diz qual.",
  "Gráfico de setores: o todo é 100%; 1% = 3,6°.",
  "Em gráfico de linhas, 'crescimento maior' é a inclinação mais íngreme, não o ponto mais alto.",
  "Desconfiar de eixo que não começa no zero — é o truque clássico para exagerar diferença."],
 armadilha:"Alternativa que é verdadeira no mundo real mas não está no gráfico. A resposta tem que sair DOS DADOS mostrados, não do seu conhecimento.",
 fogo:"Qual a diferença entre 'subiu 10 pontos percentuais' e 'subiu 10%'?"},

{area:"mat",tier:"nucleo",topico:"Sistema de duas equações do 1º grau (disfarçado)",freq:"~1 por prova, quase sempre",
 saber:["Reconhecer o formato: duas compras diferentes dos mesmos dois itens, dois preços totais. Ex.: 3 tomates + 2 alfaces = R$ 11; 2 tomates + 4 alfaces = R$ 14.",
  "Nomear com letras, escrever as duas equações e resolver por <b>substituição</b> ou <b>adição</b> (multiplicar uma linha para cancelar uma incógnita).",
  "Sempre conferir a resposta nas DUAS equações antes de marcar.",
  "Também aparece como: inteira/meia-entrada, adulto/criança, moeda de R$1 e de R$0,50."],
 armadilha:"O enunciado pede o valor de uma das incógnitas e você entrega a outra, ou entrega a soma. Sublinhe o que foi perguntado.",
 fogo:"Explique o método da adição: por que multiplicar uma equação inteira por um número não muda a resposta?"},

{area:"mat",tier:"nucleo",topico:"Conversão de unidades",freq:"~1 por prova, em todas",
 saber:["Comprimento: ×10 por degrau (km hm dam m dm cm mm). Área: ×100 por degrau. Volume: ×1000 por degrau.",
  "Tempo: 1 h = 60 min = 3600 s. Converter fração de dia: <code>0,9 dia × 24 = 21,6 h</code>, e <code>0,6 h × 60 = 36 min</code>.",
  "Capacidade × volume: <code>1 L = 1 dm³</code>, <code>1 m³ = 1000 L</code>, <code>1 mL = 1 cm³</code>.",
  "Massa: 1 t = 1000 kg = 1.000.000 g.",
  "Velocidade: de km/h para m/s <b>divide por 3,6</b>; de m/s para km/h multiplica por 3,6."],
 armadilha:"Converter 2,5 h como '2h50min'. É 2h30min — a parte decimal é fração de hora, multiplica por 60.",
 fogo:"Por que área multiplica por 100 a cada degrau e volume por 1000, se comprimento multiplica por 10?"},

{area:"mat",tier:"orbita",topico:"Teorema de Pitágoras e semelhança",freq:"~1 a cada duas provas",
 saber:["<code>a² = b² + c²</code>, com a = hipotenusa (sempre o lado oposto ao ângulo reto).",
  "Decorar os trios: <b>3-4-5</b>, 5-12-13, 6-8-10, 8-15-17. Cobre quase toda questão de prova.",
  "Aparece disfarçado em: escada na parede, diagonal de terreno/tela, altura de poste com sombra, distância percorrida em L.",
  "Semelhança: figuras com mesma forma → lados proporcionais. A razão entre áreas é o <b>quadrado</b> da razão entre lados."],
 armadilha:"Usar Pitágoras num triângulo que não é retângulo, ou chamar de hipotenusa um cateto.",
 fogo:"Como eu sei, olhando o problema, qual lado é a hipotenusa?"},

{area:"mat",tier:"orbita",topico:"Média aritmética e média ponderada",freq:"~1 a cada duas provas",
 saber:["Média simples: soma ÷ quantidade.",
  "Ponderada: <code>(n₁·p₁ + n₂·p₂) / (p₁ + p₂)</code> — divide pela soma dos PESOS, não pela quantidade de notas.",
  "Achar a nota que falta: monte a equação da média com a incógnita e resolva.",
  "Moda = o que mais aparece. Mediana = o do meio com os dados <b>em ordem</b> (com quantidade par, média dos dois centrais)."],
 armadilha:"Calcular mediana sem ordenar os números primeiro.",
 fogo:"Por que a mediana é melhor que a média para descrever o salário de um país desigual?"},

{area:"mat",tier:"orbita",topico:"Probabilidade e contagem",freq:"~1 a cada duas provas (2026.2 usou cartas de Pokémon)",
 saber:["<code>P = favoráveis / possíveis</code>. Resultado entre 0 e 1 — converter para % multiplicando por 100.",
  "Princípio multiplicativo: etapas em sequência ('e') <b>multiplicam</b>; opções excludentes ('ou') <b>somam</b>.",
  "Sem reposição, o denominador diminui na segunda retirada.",
  "Probabilidade do complementar: <code>P(não A) = 1 − P(A)</code> — atalho para 'pelo menos um'."],
 armadilha:"Somar quando deveria multiplicar (4 camisetas + 3 calças = 7 ✗; são 12 combinações ✓).",
 fogo:"Quando eu somo e quando eu multiplico as possibilidades?"},

{area:"mat",tier:"orbita",topico:"MMC, MDC, primos e divisibilidade",freq:"raro, mas cai",
 saber:["MMC = 'quando voltam a coincidir' (ônibus, luzes piscando, times se encontrando).",
  "MDC = 'maior pedaço igual' (cortar barbante, dividir em grupos iguais sem sobra).",
  "Fatorar em primos e pegar os expoentes: MMC leva os <b>maiores</b>, MDC os <b>menores</b> em comum.",
  "Critérios: por 2 (par), por 3 (soma dos algarismos), por 5 (termina em 0 ou 5), por 9 (soma divisível por 9).",
  "Primo tem exatamente dois divisores. 1 não é primo; 2 é o único primo par."],
 armadilha:"Trocar MMC por MDC. Pergunta-chave: quero um número MAIOR que os dois (MMC) ou MENOR (MDC)?",
 fogo:"Por que o MDC nunca pode ser maior que o menor dos números?"},

{area:"mat",tier:"orbita",topico:"Conjuntos numéricos e notação científica",freq:"~1 a cada duas provas",
 saber:["Racional = pode virar fração de inteiros — inclui inteiro, decimal exato e <b>dízima periódica</b>.",
  "Irracional = infinito e sem período: π, √2, √3, √5 (raiz não exata).",
  "Notação científica: um só algarismo diferente de zero antes da vírgula. <code>0,00035 = 3,5×10⁻⁴</code>.",
  "Multiplicar potências de 10 soma expoentes; dividir subtrai."],
 armadilha:"Chamar 0,333… de irracional. É 1/3, racional. O que define irracional é não ter período.",
 fogo:"√9 é racional ou irracional? E √10? Por quê?"},

{area:"mat",tier:"cauda",topico:"Equação do 2º grau, produtos notáveis e fatoração",freq:"raríssimo isolado — aparece dentro de problema de área",
 saber:["Bhaskara <code>x=(−b±√Δ)/2a</code> com <code>Δ=b²−4ac</code>; Δ>0 duas raízes, Δ=0 uma, Δ<0 nenhuma real.",
  "Soma das raízes <code>−b/a</code>, produto <code>c/a</code> — muitas vezes resolve de cabeça.",
  "<code>(a+b)² = a²+2ab+b²</code> — o erro clássico é esquecer o <code>2ab</code>.",
  "<code>a²−b² = (a+b)(a−b)</code>.",
  "Numa questão de contexto, descartar a raiz negativa: medida não é negativa."],
 armadilha:"Está no Anexo V, então dá medo. Mas se aparecer, será dentro de um problema de área, não como 'resolva a equação'. Não invista mais que uma sessão.",
 fogo:"O que o discriminante Δ está me dizendo, no gráfico?"},

{area:"mat",tier:"cauda",topico:"Função do 1º grau, juros compostos, polígonos e ângulos",freq:"raro",
 saber:["Função do 1º grau <code>y = ax + b</code>: b é onde corta o eixo y, a é a inclinação (a>0 sobe, a<0 desce).",
  "Juros simples <code>J=C·i·t</code> (base fixa). Compostos <code>M=C(1+i)ᵗ</code> (juro sobre juro).",
  "Soma dos ângulos internos de um polígono: <code>(n−2)·180°</code>. Triângulo 180°, quadrilátero 360°.",
  "Ângulos: complementares somam 90°, suplementares somam 180°, opostos pelo vértice são iguais."],
 armadilha:"Investir tempo aqui antes de dominar os seis tópicos de núcleo. Este bloco vale, no máximo, meia questão.",
 fogo:"Qual a diferença prática entre juros simples e compostos depois de 3 meses?"},

/* ========================= CIÊNCIAS ========================= */
{area:"cie",tier:"nucleo",topico:"Energia: fontes, transformações e matriz energética",freq:"1 a 2 por prova, em todas",
 saber:["Renovável: hidrelétrica, solar, eólica, biomassa, maré. Não renovável: petróleo, carvão, gás natural, urânio.",
  "A matriz elétrica brasileira é dominada por <b>hidrelétricas</b>; a mundial ainda é dominada por combustíveis fósseis.",
  "Energia não é criada nem destruída, só <b>transformada</b>: química→elétrica (pilha), elétrica→luminosa+térmica (lâmpada), potencial gravitacional→cinética→elétrica (usina).",
  "Toda transformação real dissipa parte como calor — por isso rendimento nunca é 100%.",
  "Fóssil libera CO₂ e intensifica o efeito estufa; renovável tem impacto menor, mas não é zero (hidrelétrica alaga área, eólica afeta aves)."],
 armadilha:"Confundir 'energia limpa' com 'energia renovável'. Nuclear é pouco emissora de CO₂ mas NÃO é renovável; biomassa é renovável mas emite.",
 fogo:"Siga a energia de uma usina hidrelétrica até a lâmpada da sua casa, nomeando cada transformação."},

{area:"cie",tier:"nucleo",topico:"Eletricidade e consumo (seu terreno)",freq:"1 a 2 por prova",
 saber:["Corrente (A) é fluxo de carga; tensão (V) é o empurrão; resistência (Ω) é a oposição. <code>U = R·I</code>.",
  "Potência <code>P = U·I</code>, em watts. Energia consumida <code>E = P × tempo</code>.",
  "<b>kWh é a unidade da conta de luz</b>: <code>kWh = (watts ÷ 1000) × horas</code>. Custo = kWh × tarifa. Isso cai como questão de matemática disfarçada.",
  "Série: mesma corrente em todos, a tensão se divide, uma lâmpada queima e apaga tudo. Paralelo: mesma tensão em todos, a corrente se divide, é assim que a casa é ligada.",
  "Condutor (metais) × isolante (borracha, vidro, plástico). Curto-circuito, aterramento e a função do disjuntor."],
 armadilha:"Somar watts e horas, ou esquecer de dividir por 1000 ao passar de W para kW.",
 fogo:"Um chuveiro de 5500 W ligado 20 min por dia gasta quantos kWh no mês? Faça em voz alta."},

{area:"cie",tier:"nucleo",topico:"Calor, temperatura e propagação",freq:"~1 por prova",
 saber:["Temperatura mede agitação das partículas; calor é energia <b>em trânsito</b> do mais quente para o mais frio.",
  "Condução: contato, precisa de meio material — colher de metal na panela.",
  "Convecção: correntes em fluidos, o quente sobe e o frio desce — geladeira com congelador em cima, ar-condicionado no alto.",
  "Irradiação: ondas eletromagnéticas, <b>funciona no vácuo</b> — é assim que o calor do Sol chega à Terra.",
  "Equilíbrio térmico: dois corpos em contato terminam na mesma temperatura. Isolante térmico (isopor, garrafa térmica) atrasa isso."],
 armadilha:"Dizer que 'o agasalho esquenta o corpo'. Ele não produz calor — reduz a perda dele para fora.",
 fogo:"Por que o calor do Sol chega até nós se o espaço é vácuo?"},

{area:"cie",tier:"nucleo",topico:"Célula: estrutura e funções",freq:"~1 por prova, em todas",
 saber:["Membrana plasmática (controla entrada e saída), citoplasma, núcleo (guarda o DNA).",
  "Procarionte (bactéria) <b>não tem núcleo definido</b>; eucarionte (animal, vegetal, fungo, protozoário) tem.",
  "Célula vegetal tem, a mais: <b>parede celular</b>, <b>cloroplasto</b> e vacúolo grande.",
  "Mitocôndria = respiração celular (produz ATP). Cloroplasto = fotossíntese. Ribossomo = proteína.",
  "Osmose: a água vai do meio menos concentrado para o mais concentrado — é por isso que a salada murcha com sal."],
 armadilha:"Achar que célula vegetal não tem mitocôndria. Tem — a planta também respira, inclusive de noite.",
 fogo:"Cite três estruturas que a célula vegetal tem e a animal não, dizendo para que servem."},

{area:"cie",tier:"nucleo",topico:"Fotossíntese e respiração celular",freq:"~1 por prova",
 saber:["Fotossíntese: <code>CO₂ + água + luz → glicose + O₂</code>. Ocorre no cloroplasto, só com luz.",
  "Respiração celular: <code>glicose + O₂ → CO₂ + água + energia (ATP)</code>. Ocorre na mitocôndria, <b>24 horas por dia</b>, na planta também.",
  "São processos inversos e complementares — um usa o produto do outro.",
  "A planta é <b>produtora</b>: transforma energia luminosa em energia química, e é a base de toda cadeia alimentar.",
  "Ligação com o clima: a floresta estoca carbono; desmatar e queimar devolve esse carbono para a atmosfera."],
 armadilha:"Dizer que a planta respira de dia e faz fotossíntese de noite, ou que ela só respira à noite. Ela respira sempre; a fotossíntese é que depende de luz.",
 fogo:"Se a planta produz O₂, por que ela também precisa de O₂?"},

{area:"cie",tier:"nucleo",topico:"Corpo humano: sistemas integrados",freq:"~1 por prova",
 saber:["Digestório: boca→esôfago→estômago→intestino delgado (<b>onde ocorre a absorção</b>)→intestino grosso (água)→ânus.",
  "Respiratório: a troca gasosa acontece nos <b>alvéolos</b>; o diafragma comanda a mecânica.",
  "Circulatório: pequena circulação coração↔pulmão (oxigena); grande circulação coração↔corpo. Artéria sai do coração, veia chega.",
  "Excretor: o rim filtra o sangue e forma a urina — controla também água e sais.",
  "Nervoso: sistema nervoso central (encéfalo + medula) e periférico (nervos). Arco reflexo passa pela medula, sem ir ao cérebro."],
 armadilha:"'Artéria leva sangue oxigenado' é falso na artéria pulmonar, que leva sangue venoso ao pulmão. A definição correta é pela direção: artéria SAI do coração.",
 fogo:"Descreva o caminho de uma molécula de O₂ do ar até uma célula do seu pé."},

{area:"cie",tier:"nucleo",topico:"Vírus, bactérias, vacinas e ISTs",freq:"~1 por prova — tema recorrente desde 2020",
 saber:["Vírus é parasita intracelular obrigatório, <b>não é célula</b> e não responde a antibiótico. Bactéria é célula e responde.",
  "Vacina = imunização <b>ativa</b>: apresenta o antígeno, o corpo produz anticorpos e memória. Soro = imunização <b>passiva</b>: já contém anticorpos prontos, age rápido e é tratamento, não prevenção.",
  "Imunidade coletiva: cobertura vacinal alta protege quem não pode se vacinar. Queda na cobertura traz doença de volta (sarampo, poliomielite).",
  "ISTs: HIV/aids, sífilis, gonorreia, HPV (tem vacina no SUS), hepatite B (tem vacina). Prevenção: preservativo, testagem, vacinação.",
  "Doenças por vetor: dengue, zika, chikungunya (Aedes aegypti) — prevenção é eliminar água parada."],
 armadilha:"Tomar antibiótico para gripe. Antibiótico não age em vírus, e o uso errado gera bactéria resistente.",
 fogo:"Qual a diferença entre vacina e soro, e quando eu usaria cada um?"},

{area:"cie",tier:"nucleo",topico:"Átomo, elementos e tabela periódica",freq:"1 a 2 por prova",
 saber:["Prótons (+) e nêutrons no núcleo; elétrons (−) na eletrosfera. <code>Z = nº de prótons</code> (identifica o elemento), <code>A = prótons + nêutrons</code>.",
  "Átomo neutro: prótons = elétrons. <b>Íon</b>: cátion perdeu elétron (fica +), ânion ganhou elétron (fica −).",
  "Isótopos: mesmo Z, A diferente (mesmo elemento, massas diferentes).",
  "Na tabela: período = linha, família/grupo = coluna. Metais, ametais e gases nobres (estáveis, não reagem).",
  "Substância simples = um só elemento (O₂, Fe). Composta = mais de um (H₂O, NaCl)."],
 armadilha:"Somar A e Z para achar os nêutrons. Nêutrons = <b>A − Z</b>.",
 fogo:"Um átomo com Z=11 perdeu um elétron. Qual a carga dele e quantos elétrons tem agora?"},

{area:"cie",tier:"nucleo",topico:"Misturas, separação e transformações",freq:"1 a 2 por prova",
 saber:["Mistura homogênea (uma fase só: água+sal, ar, aço) × heterogênea (fases visíveis: água+óleo, granito).",
  "Separação: filtração (sólido em líquido), decantação (densidades diferentes), destilação (separa líquidos por ponto de ebulição), evaporação, catação, peneiração, imantação, centrifugação.",
  "Transformação <b>física</b>: muda o estado ou a forma, a substância continua a mesma (gelo derretendo, papel rasgado, sal dissolvido).",
  "Transformação <b>química</b>: forma substância nova. Sinais: mudança de cor, liberação de gás, precipitado, cheiro novo, liberação/absorção de calor.",
  "Mudanças de estado: fusão, vaporização, condensação, solidificação, sublimação."],
 armadilha:"Chamar dissolução de sal de reação química. É física — dá para recuperar o sal evaporando a água.",
 fogo:"Como eu separo areia, sal e água de um mesmo copo? Em que ordem e por quê?"},

{area:"cie",tier:"nucleo",topico:"Astronomia: Terra, Lua e Sol",freq:"~1 por prova — bloco minúsculo, ROI altíssimo",
 saber:["Rotação (~24 h) → dia e noite. Translação (~365 dias) + <b>inclinação do eixo</b> → estações do ano.",
  "As estações NÃO vêm da distância ao Sol — vêm da inclinação, que muda a incidência dos raios. Por isso os hemisférios têm estações opostas.",
  "Fases da Lua: nova, crescente, cheia, minguante, ciclo de ~29,5 dias. A Lua mostra sempre a mesma face (rotação sincronizada).",
  "Eclipse solar: Lua entre Terra e Sol (fase nova). Eclipse lunar: Terra entre Sol e Lua (fase cheia).",
  "<b>Massa</b> é a quantidade de matéria e não muda de lugar; <b>peso</b> é força da gravidade e muda (na Lua o peso é ~1/6, a massa é a mesma). Marés são efeito da atração Lua–Sol."],
 armadilha:"Explicar o verão dizendo que a Terra está mais perto do Sol. Está errado — e o hemisfério sul prova isso.",
 fogo:"Por que é verão no Brasil quando é inverno na Europa?"},

{area:"cie",tier:"orbita",topico:"Ecologia, cadeia alimentar e ciclos",freq:"~1 a cada duas provas",
 saber:["Cadeia: produtor → consumidor 1º → 2º → 3º, com decompositores fechando o ciclo.",
  "A energia <b>diminui</b> a cada nível (só ~10% passa adiante) — por isso a pirâmide de energia nunca é invertida.",
  "Relações: predatismo, competição, mutualismo, comensalismo, parasitismo.",
  "Ciclo da água, do carbono e do nitrogênio; bioacumulação de poluentes ao longo da cadeia.",
  "Espécie nativa × exótica invasora; extinção e perda de biodiversidade."],
 armadilha:"Inverter o sentido das setas da cadeia alimentar. A seta aponta para quem RECEBE a energia (capim → gafanhoto).",
 fogo:"Por que uma cadeia alimentar raramente tem mais de cinco níveis?"},

{area:"cie",tier:"orbita",topico:"Evolução e genética básica",freq:"~1 alternando com ecologia",
 saber:["Lamarck: uso e desuso + herança de caracteres adquiridos — <b>refutado</b>. Darwin: variação + seleção natural — aceito.",
  "A seleção natural age sobre variações que <b>já existiam</b>; o ambiente não cria a característica, ele filtra.",
  "Evidências: fósseis, órgãos homólogos e análogos, DNA.",
  "1ª Lei de Mendel: cada característica vem de um par de alelos que se separam nos gametas. Cruzar <code>Aa × Aa</code> → 1 AA : 2 Aa : 1 aa → <b>3 dominantes : 1 recessivo</b>.",
  "Genótipo é a combinação de alelos; fenótipo é a característica que aparece."],
 armadilha:"Dizer que 'a girafa esticou o pescoço para alcançar as folhas'. Isso é Lamarck e está errado — as de pescoço maior já existiam e sobreviveram mais.",
 fogo:"Explique a resistência bacteriana a antibióticos usando seleção natural."},

{area:"cie",tier:"orbita",topico:"Movimento, força, ondas, som e luz",freq:"~1 a cada duas provas",
 saber:["Velocidade média <code>v = Δs/Δt</code>. Cuidado com a unidade (km/h ÷ 3,6 = m/s).",
  "Som precisa de meio material — <b>não se propaga no vácuo</b>. Luz se propaga no vácuo.",
  "Luz: reflexão (espelho), refração (canudo 'quebrado' na água), a luz branca se decompõe em cores (arco-íris).",
  "Onda tem frequência (Hz), amplitude (intensidade/volume) e comprimento de onda.",
  "Força: ação e reação; atrito atrapalha mas permite andar e frear."],
 armadilha:"Achar que explosão no espaço faz barulho. Vácuo não transmite som.",
 fogo:"Por que você vê o relâmpago antes de ouvir o trovão?"},

{area:"cie",tier:"cauda",topico:"Ligações químicas, reações, ácidos e bases",freq:"raro",
 saber:["Iônica (metal + ametal, transfere elétron, forma sal), covalente (compartilha elétron), metálica.",
  "Reação balanceada: mesma quantidade de cada átomo dos dois lados (Lei de Lavoisier — nada se perde).",
  "pH: <7 ácido, 7 neutro, >7 básico. Ácido + base → sal + água (neutralização).",
  "Exemplos do cotidiano: vinagre e limão (ácidos), sabão e leite de magnésia (bases), chuva ácida."],
 armadilha:"Está no Anexo V, mas historicamente rende menos de uma questão. Saber reconhecer, não decorar tabela de valências.",
 fogo:"Por que antiácido alivia azia?"},

{area:"cie",tier:"cauda",topico:"Densidade, empuxo e máquinas simples",freq:"raro",
 saber:["<code>d = m/V</code>. Menos denso que o líquido → flutua; mais denso → afunda. Por isso o óleo fica sobre a água.",
  "Empuxo é a força de baixo para cima que o líquido faz; navio de aço flutua porque o casco é oco e a densidade MÉDIA é baixa.",
  "Alavanca, roldana e plano inclinado reduzem a força necessária, nunca o trabalho total.",
  "Pressão <code>p = F/A</code>: área menor, pressão maior (por isso a faca afiada corta melhor)."],
 armadilha:"Confundir massa com densidade — 1 kg de chumbo e 1 kg de algodão têm a mesma massa e densidades muito diferentes.",
 fogo:"Como um navio de aço flutua se o aço afunda?"},

/* ===================== GEOGRAFIA E HISTÓRIA ===================== */
{area:"gh",tier:"nucleo",topico:"Escravidão, resistência e abolicionismo",freq:"1 a 2 por prova — apareceu em TODAS as provas analisadas",
 saber:["Tráfico atlântico, diáspora africana e a escravidão como base econômica da colônia e do Império — cana, mineração, café.",
  "<b>Resistência</b> é o coração do tema: quilombos (Palmares, Zumbi, Dandara), fugas, revoltas (Malês 1835, Balaiada, Cabanagem), capoeira, religiosidade e preservação cultural.",
  "Leis do fim gradual: Eusébio de Queirós 1850 (fim do tráfico), Ventre Livre 1871, Sexagenários 1885, <b>Lei Áurea 13/05/1888</b>.",
  "A abolição não veio acompanhada de terra, escola ou trabalho — daí a desigualdade racial estrutural que persiste.",
  "Protagonismo negro: Luiz Gama, José do Patrocínio, André Rebouças, Maria Firmina dos Reis, Tereza de Benguela. Movimento negro, Lei 10.639/2003 (ensino de história e cultura afro-brasileira), cotas."],
 armadilha:"A alternativa que trata o negro escravizado como agente passivo, ou que apresenta a Princesa Isabel como causa única da abolição. O IFSC valoriza <b>resistência e protagonismo</b> — quase sempre a resposta certa está aí.",
 fogo:"Cite três formas diferentes de resistência à escravidão e explique por que a Lei Áurea não encerrou a desigualdade."},

{area:"gh",tier:"nucleo",topico:"Santa Catarina: história, ocupação e território",freq:"1 a 2 por prova — cai em Geografia E em História",
 saber:["Ocupação: indígenas (Xokleng/Laklãnõ, Kaingang, Guarani), açorianos no litoral (século XVIII), alemães (Blumenau, Joinville) e italianos (Criciúma, sul) no XIX.",
  "<b>Guerra do Contestado (1912–1916)</b>: disputa de terras entre SC e PR, ferrovia Brasil Railway, expulsão de posseiros, messianismo do Monge José Maria, repressão do Exército. É o evento mais cobrado de SC.",
  "Mesorregiões: Litoral/Grande Florianópolis (serviços, turismo, tecnologia), Vale do Itajaí (têxtil), Norte (metalmecânica, Joinville), Oeste (agroindústria, aves e suínos), Serra (pecuária, turismo de frio), Sul (carvão, cerâmica).",
  "Ambiente: Mata Atlântica e Araucária muito reduzidas, carvão do sul e passivo ambiental, enchentes do Vale do Itajaí, erosão costeira, dunas e manguezais.",
  "Economia: indústria diversificada, forte peso do agronegócio no Oeste, porto de Itajaí/Navegantes, turismo no litoral."],
 armadilha:"Reduzir SC a 'colonização alemã'. A ocupação é plural — indígena, açoriana, africana, alemã, italiana — e a prova cobra essa pluralidade.",
 fogo:"Explique a Guerra do Contestado: quem disputava o quê, e por quê."},

{area:"gh",tier:"nucleo",topico:"Meio ambiente, biomas e mudança climática",freq:"1 a 2 por prova — e ainda reaparece em Ciências",
 saber:["Biomas brasileiros: Amazônia (floresta equatorial úmida), Cerrado (savana, berço das águas), Mata Atlântica (mais devastada, ~12% restantes), Caatinga (semiárido, exclusivamente brasileiro), Pampa, Pantanal (maior planície alagável).",
  "Desmatamento e queimadas: expansão agropecuária, grilagem, garimpo. Consequências: perda de biodiversidade, emissão de carbono, alteração do regime de chuvas ('rios voadores').",
  "<b>Efeito estufa é natural e necessário</b>; o problema é a intensificação pela queima de combustível fóssil e desmatamento.",
  "Diferenciar: efeito estufa (CO₂, CH₄ — aquecimento) × buraco na camada de ozônio (CFCs — radiação UV). São problemas distintos.",
  "Urbano: ilha de calor, impermeabilização e enchentes, lixo e coleta seletiva, saneamento. Acordos: Rio-92, Protocolo de Kyoto, Acordo de Paris, ODS."],
 armadilha:"Misturar efeito estufa com camada de ozônio. É a confusão mais explorada em prova de todo o Brasil.",
 fogo:"Qual a diferença entre efeito estufa e buraco na camada de ozônio — causa, gás e consequência?"},

{area:"gh",tier:"nucleo",topico:"Brasil república: Vargas, ditadura e redemocratização",freq:"~1 por prova",
 saber:["Era Vargas 1930–1945: CLT e direitos trabalhistas, mas também <b>Estado Novo (1937–45)</b> — ditadura, censura (DIP), repressão. Nacionalismo econômico (CSN, Petrobras no 2º governo).",
  "Ditadura militar 1964–1985: golpe contra João Goulart, <b>AI-5 (1968)</b> como ponto de virada, censura, tortura, desaparecidos, bipartidarismo. 'Milagre econômico' com concentração de renda e endividamento.",
  "Resistência: estudantes, artistas (Tropicália, MPB de protesto), imprensa alternativa, Igreja, Diretas Já (1984).",
  "Redemocratização: anistia 1979, eleição de Tancredo/Sarney 1985, <b>Constituição de 1988</b> ('Constituição Cidadã'), eleição direta 1989.",
  "CF/88: direitos sociais, SUS, racismo como crime inafiançável, direitos indígenas e quilombolas."],
 armadilha:"Alternativa que apresenta a ditadura só pelo 'milagre econômico' sem o custo social, ou Vargas só como 'pai dos pobres' sem o Estado Novo. A prova cobra a ambiguidade dos dois períodos.",
 fogo:"O que o AI-5 mudou na prática, e por que 1968 é considerado o ano da virada?"},

{area:"gh",tier:"nucleo",topico:"Guerra Fria e geopolítica do século XX",freq:"~1 por prova",
 saber:["1947–1991: EUA (capitalismo, OTAN, Plano Marshall) × URSS (socialismo, Pacto de Varsóvia, Comecon). Mundo bipolar.",
  "Conflito indireto: corrida armamentista e espacial, Coreia, Vietnã, Cuba, golpes na América Latina.",
  "Muro de Berlim (1961–1989) como símbolo; queda em 1989 e fim da URSS em 1991.",
  "Descolonização da África e da Ásia no pós-guerra; conceito de Terceiro Mundo.",
  "Depois de 1991: hegemonia dos EUA, e no século XXI um mundo <b>multipolar</b> com China, UE, Rússia, Índia e os BRICS."],
 armadilha:"Dizer que houve guerra direta entre EUA e URSS. Nunca houve — o confronto foi por procuração, e é isso que o nome 'fria' significa.",
 fogo:"Por que se chama Guerra 'Fria' se morreu tanta gente na Coreia e no Vietnã?"},

{area:"gh",tier:"nucleo",topico:"Globalização, trabalho e tecnologia",freq:"~1 por prova",
 saber:["Globalização: integração de mercados, fluxo de capital, cadeias produtivas globais, empresas transnacionais, revolução dos transportes e da informação.",
  "Fases do trabalho: taylorismo/fordismo (linha de montagem, produção em massa, estoque) → <b>toyotismo</b> (flexível, just-in-time, multifuncional) → automação, plataformas e uberização.",
  "Consequências: desemprego estrutural, informalidade, precarização, exigência de qualificação — e a desigualdade entre países centrais e periféricos.",
  "Divisão internacional do trabalho: periferia exporta commodity (soja, minério), centro exporta tecnologia e agrega valor.",
  "Inclusão digital, IA e automação: o que muda para quem está entrando no mercado de trabalho agora."],
 armadilha:"Alternativa que diz que a globalização integrou o mundo 'de forma homogênea'. Ela é seletiva e desigual — é sempre esse o ponto que a prova quer.",
 fogo:"Qual a diferença entre fordismo e toyotismo, e o que isso mudou para o trabalhador?"},

{area:"gh",tier:"nucleo",topico:"Direitos humanos, desigualdade e diversidade",freq:"~1 por prova — valor explícito no edital",
 saber:["Declaração Universal dos Direitos Humanos (1948) e a Constituição de 1988 como marcos.",
  "Racismo estrutural, desigualdade de renda, acesso desigual a educação e saúde; ações afirmativas e cotas como política de reparação.",
  "Gênero: desigualdade salarial, divisão do trabalho doméstico, violência contra a mulher (Lei Maria da Penha 2006, Lei do Feminicídio 2015).",
  "<b>Povos indígenas</b>: diversidade de povos e línguas, demarcação de terras, Constituição de 1988, conflitos com garimpo e agronegócio, caso Yanomami. Povos quilombolas e comunidades tradicionais.",
  "Migrações e refugiados; xenofobia; direito à cidade e ao saneamento."],
 armadilha:"Alternativa que trata desigualdade como resultado de mérito individual. A prova adota o enfoque estrutural e histórico — é isso que ela quer ver reconhecido.",
 fogo:"Por que política de cotas é tratada como reparação e não como privilégio? Argumente."},

{area:"gh",tier:"orbita",topico:"População, urbanização e migrações",freq:"~1 a cada duas provas",
 saber:["Pirâmide etária: base larga = população jovem; o Brasil está <b>envelhecendo</b> — base estreitando, topo alargando.",
  "Transição demográfica: queda da mortalidade e depois da natalidade. Consequência: pressão na previdência, 'bônus demográfico' acabando.",
  "Êxodo rural do século XX → urbanização acelerada → periferias, favelas, déficit de saneamento e moradia.",
  "Migrações internas: nordestinos para o Sudeste; hoje, migração de retorno e fluxo para o Centro-Oeste e o Sul.",
  "Indicadores: IDH (renda, educação, longevidade), expectativa de vida, densidade demográfica."],
 armadilha:"Ler pirâmide etária invertendo os eixos, ou confundir crescimento vegetativo com crescimento total (que inclui migração).",
 fogo:"O que significa a pirâmide etária brasileira estar com a base mais estreita?"},

{area:"gh",tier:"orbita",topico:"Cartografia, clima e relevo",freq:"~1 a cada duas provas",
 saber:["Escala: quanto maior o denominador, <b>menor</b> a escala e menos detalhe (1:1.000 é mais detalhado que 1:1.000.000).",
  "Coordenadas: latitude (paralelos, Equador 0°) e longitude (meridianos, Greenwich 0°). Fusos horários a partir de Greenwich.",
  "Projeções deformam algo: Mercator preserva forma e exagera as áreas polares; Peters preserva área e distorce forma.",
  "Clima × tempo: clima é o padrão de muitos anos, tempo é o de hoje. Fatores: latitude, altitude, maritimidade, correntes marítimas.",
  "Climas do Brasil: equatorial, tropical, tropical semiárido, tropical de altitude, <b>subtropical (Sul, inclui SC)</b>. Relevo: planalto, planície, depressão."],
 armadilha:"Achar que escala 1:1.000.000 é 'grande'. É escala PEQUENA — cobre muita área com pouco detalhe.",
 fogo:"Por que o mapa de Mercator faz a Groenlândia parecer do tamanho da África?"},

{area:"gh",tier:"orbita",topico:"Formação do Brasil: colônia, Império e República Velha",freq:"~1 a cada duas provas",
 saber:["Ciclos econômicos: pau-brasil, açúcar (Nordeste, engenho, escravidão), mineração (Minas, século XVIII, urbanização e Inconfidência), café (Sudeste, XIX).",
  "Independência 1822: processo conduzido pela elite, mantendo escravidão e monarquia.",
  "Segundo Reinado, Guerra do Paraguai, crise da monarquia e Proclamação da República (1889) — golpe militar sem participação popular.",
  "República Velha (1889–1930): café com leite, coronelismo, voto de cabresto, revoltas (Canudos, Contestado, Vacina, Chibata), imigração europeia.",
  "Modernismo de 1922 e tenentismo como sinais da crise que leva a 1930."],
 armadilha:"Tratar a Independência e a República como rupturas populares. Ambas foram arranjos de elite — a prova costuma cobrar exatamente essa leitura.",
 fogo:"Por que se diz que a Proclamação da República foi feita 'sem povo'?"},

{area:"gh",tier:"orbita",topico:"Economia brasileira: agropecuária, indústria e regiões",freq:"~1 a cada duas provas",
 saber:["Agronegócio: soja, milho, carne, cana; expansão pelo MATOPIBA e Centro-Oeste; forte peso nas exportações e nas emissões.",
  "Agricultura familiar responde por grande parte do alimento da mesa brasileira; PRONAF, reforma agrária, conflito por terra.",
  "Industrialização: substituição de importações, Plano de Metas (JK), concentração no Sudeste e posterior desconcentração para Sul e Nordeste.",
  "Regiões do IBGE e suas marcas: Sudeste (indústria e serviços), Sul (agroindústria e indústria diversificada), Nordeste (turismo, petroquímica, energia eólica), Norte (Zona Franca, floresta), Centro-Oeste (agronegócio).",
  "Matriz de transporte brasileira é rodoviária, cara e ineficiente — a prova gosta de comparar com ferrovia e hidrovia."],
 armadilha:"Confundir agronegócio com agricultura familiar. São modelos diferentes em escala, destino da produção e política pública.",
 fogo:"Por que depender de rodovia encarece o produto brasileiro?"},

/* ---------- História Geral (Anexo V), na ordem do edital ---------- */
{area:"gh",tier:"cauda",topico:"História Antiga e as primeiras sociedades",freq:"não caiu como tema próprio em 2023.2–2026.2, mas está no Anexo V",
 saber:["Mesopotâmia (Tigre e Eufrates) e Egito (Nilo): agricultura irrigada, cidades, Estado teocrático, escrita (cuneiforme na Suméria, c. 3200 a.C.; hieróglifos no Egito).",
  "Código de Hamurábi (Babilônia, c. 1750 a.C.): lei de talião (“olho por olho”), mas com penas <b>diferentes conforme a posição social</b> — livre, dependente, escravo.",
  "Atenas, século V a.C.: democracia <b>direta</b> (Eclésia), mas cidadania restrita a homens adultos atenienses. Mulheres, escravizados e metecos ficavam de fora. Esparta: oligarquia militar com dois reis.",
  "Roma: monarquia → república (patrícios × plebeus, tribunos da plebe, Lei das Doze Tábuas) → império. Herança: o direito romano, base do direito brasileiro.",
  "Cristianismo em Roma: perseguido (Nero, Diocleciano) → tolerado no Édito de Milão (313, Constantino) → religião oficial com Teodósio (380)."],
 armadilha:"Anacronismo: atribuir à Antiguidade valores de hoje, como “igualdade perante a lei” ou uma democracia que incluía todos. A banca adora a alternativa que chama Atenas de democracia universal.",
 fogo:"Por que a democracia ateniense não seria considerada democrática hoje?"},

{area:"gh",tier:"cauda",topico:"Idade Média e expansão islâmica",freq:"não caiu como tema próprio em 2023.2–2026.2, mas está no Anexo V",
 saber:["Feudalismo: terra como riqueza, economia agrária, relação de suserania e vassalagem entre nobres, servos <b>presos à terra</b> pagando corveia, talha e banalidades.",
  "Sociedade estamental — “uns oram, outros combatem, outros trabalham” (Adalberão de Laon, séc. XI): posição pelo nascimento, desigualdade apresentada como vontade de Deus.",
  "Igreja: maior proprietária de terras, controle da escrita e do ensino (mosteiros copistas, primeiras universidades), condenação da usura. Cisma do Oriente (1054) <b>separou</b> Roma e Constantinopla. Cruzadas a partir de 1095 (Urbano II).",
  "Islã: Maomé, Hégira (migração de Meca para Medina, <b>622</b>, ano 1 do calendário islâmico). Expansão rápida, da Península Ibérica à Ásia Central.",
  "Al-Andalus: muçulmanos na Península Ibérica de 711 a 1492 (queda de Granada). Herança: algarismos indianos difundidos pelos árabes, álgebra, medicina, tradução dos gregos, e palavras como azeite, arroz, açúcar, alface."],
 armadilha:"Tratar a Idade Média como “idade das trevas” sem ciência, ou o mundo islâmico como atrasado: na mesma época, Bagdá e Córdoba eram centros de saber que preservaram e ampliaram a ciência grega.",
 fogo:"Por que o bispo descrevia a sociedade como “a casa de Deus” dividida em três? A quem isso servia?"},

{area:"gh",tier:"cauda",topico:"Renascimento e Modernidade",freq:"não caiu como tema próprio em 2023.2–2026.2, mas está no Anexo V",
 saber:["Renascimento (séculos XIV–XVI, começa nas cidades italianas): humanismo, <b>antropocentrismo</b>, racionalismo, retorno aos clássicos greco-romanos.",
  "Antropocentrismo não é ateísmo: os artistas seguiram pintando temas religiosos (Michelangelo na Capela Sistina). Muda o foco — o homem como “artífice de si mesmo” (Pico della Mirandola, 1486).",
  "Mecenato: banqueiros, príncipes e papas financiando artistas (os Médici em Florença). A arte nasce onde está o dinheiro do comércio.",
  "Imprensa de tipos móveis (Gutenberg, Mainz, c. 1450): livro barato, ideias circulando rápido — base da Reforma de 1517.",
  "Revolução científica: heliocentrismo de Copérnico, Galileu e a observação/experimentação."],
 armadilha:"Confundir o Renascimento (séc. XV–XVI, arte e humanismo) com o Iluminismo (séc. XVIII, crítica política ao absolutismo). Ambos valorizam a razão, mas em séculos e com objetivos diferentes.",
 fogo:"O que muda na forma de ver o ser humano entre a Idade Média e o Renascimento?"},

{area:"gh",tier:"cauda",topico:"Estados Nacionais e absolutismo",freq:"não caiu como tema próprio em 2023.2–2026.2, mas está no Anexo V",
 saber:["Centralização (séc. XIV–XVII): rei concentra exército permanente, impostos, justiça, burocracia e moeda únicos. Portugal é pioneiro (Revolução de Avis, 1383–1385).",
  "<b>Aliança rei-burguesia</b>: o rei ganha recursos, a burguesia ganha mercado unificado e proteção. A nobreza perde poder político, mas mantém privilégios e isenções.",
  "Mercantilismo: metalismo (acumular ouro e prata), balança comercial favorável, protecionismo e <b>pacto colonial</b> — a colônia existe para enriquecer a metrópole.",
  "Teóricos: Hobbes (Leviatã, 1651 — sem Estado, “guerra de todos contra todos”; contrato racional) e Bossuet (direito divino dos reis). “O Estado sou eu”, atribuída a Luís XIV."],
 armadilha:"Trocar os teóricos: Hobbes justifica o poder absoluto pela razão e pelo medo, não por Deus (isso é Bossuet). E Locke, que vem depois, é o oposto: governo limitado e direito de resistência.",
 fogo:"Por que a burguesia, que depois derrubaria os reis absolutos, apoiou a centralização no começo?"},

{area:"gh",tier:"cauda",topico:"Reforma Protestante e Contrarreforma",freq:"não caiu como tema próprio em 2023.2–2026.2, mas está no Anexo V — e liga com jesuítas no Brasil",
 saber:["Lutero, 1517, 95 teses: contra a venda de indulgências. Salvação <b>pela fé</b>, Bíblia como autoridade, livre leitura, tradução para o alemão. Excomungado em 1521.",
  "Calvino (Genebra): <b>predestinação</b>; trabalho e prosperidade como sinal de eleição. Max Weber ligou essa ética ao “espírito do capitalismo”.",
  "Anglicanismo: Henrique VIII rompe com Roma para anular o casamento; Ato de Supremacia (1534) — o rei é o chefe da Igreja.",
  "Contrarreforma: Concílio de Trento (1545–1563) reafirma fé <b>e</b> obras, sete sacramentos, autoridade do papa, missa em latim; Índice de Livros Proibidos; Inquisição.",
  "Companhia de Jesus (Inácio de Loyola): ensino e catequese. No Brasil desde 1549 (Nóbrega, com Tomé de Sousa); Anchieta e a gramática tupi; aldeamentos que transformaram o modo de vida indígena."],
 armadilha:"Misturar as vertentes: predestinação é Calvino, não Lutero. E achar que Trento cedeu a Lutero — Trento reafirmou tudo o que Lutero negava.",
 fogo:"Por que a imprensa de Gutenberg foi decisiva para a Reforma dar certo, quando reformadores anteriores tinham fracassado?"},

{area:"gh",tier:"orbita",topico:"Expansionismo marítimo europeu e colonização da América",freq:"apareceu em 2026.2 (Carta de Caminha e o mito do encontro pacífico); o resto do tema é raro, mas cai pela porta da colonização do Brasil",
 saber:["Pioneirismo português: centralização precoce (Avis), posição atlântica, apoio da burguesia, técnicas náuticas (caravela, bússola, astrolábio). Ceuta 1415 → Cabo da Boa Esperança 1488 → Índia 1498 → Brasil 1500.",
  "Motivos: especiarias e metais (rota sem os intermediários italianos), mercantilismo e expansão da fé.",
  "Tordesilhas (1494): 370 léguas a oeste de Cabo Verde; leste para Portugal. Ignorou os povos nativos; França, Inglaterra e Holanda não reconheceram.",
  "Conquista espanhola: Cortés (astecas, com aliados tlaxcaltecas) e Pizarro (incas, em guerra civil). Catástrofe demográfica por guerra, trabalho forçado e <b>epidemias</b>. Denúncia de Las Casas (1552).",
  "Trabalho colonial: <b>mita</b> (minas, Potosí) e <b>encomienda</b> na América espanhola; <b>plantation</b> (latifúndio + monocultura + escravidão + exportação) no Brasil e no sul da América inglesa.",
  "Visão crítica: a divisão “povoamento × exploração” é simplista — houve escravidão nas colônias inglesas do sul e tomada de terras indígenas no norte."],
 armadilha:"Repetir a narrativa do “descobrimento” e do encontro pacífico. A prova de 2026.2 pediu justamente para identificar esse mito na Carta de Caminha. Terra com milhões de habitantes não foi “descoberta”.",
 fogo:"Por que poucas centenas de espanhóis conseguiram derrubar impérios de milhões de pessoas? Dê pelo menos três motivos."},

{area:"gh",tier:"orbita",topico:"Iluminismo e revoluções burguesas",freq:"não caiu como tema próprio em 2023.2–2026.2, mas é base de Direitos Humanos, que cai em toda prova",
 saber:["Iluministas: Locke (vida, liberdade, propriedade; direito de resistência), Montesquieu (<b>três poderes</b>, “o poder freie o poder”), Rousseau (vontade geral, soberania popular, “o homem nasceu livre e por toda parte está a ferros”), Voltaire (tolerância, liberdade de expressão).",
  "Revolução Inglesa: Puritana (1640s, Carlos I executado em 1649, república de Cromwell) e Gloriosa (1688): Bill of Rights (1689) — rei não suspende lei nem cobra imposto sem o Parlamento → monarquia parlamentar.",
  "Independência dos EUA (1776): direitos inalienáveis à vida, à liberdade e à busca da felicidade; república federativa — mas manteve a escravidão até 1865.",
  "Revolução Francesa (1789): Estados Gerais → Bastilha (14/07/1789) → Declaração dos Direitos do Homem e do Cidadão → monarquia constitucional com voto censitário (1791) → república, execução de Luís XVI (1793) e Terror jacobino → Diretório → 18 Brumário (1799), Napoleão.",
  "Limites da igualdade burguesa: Olympe de Gouges (Declaração dos Direitos da Mulher e da Cidadã, 1791; guilhotinada em 1793); escravidão colonial abolida só em 1794 e restabelecida por Napoleão em 1802."],
 armadilha:"Trocar as ideias de cada iluminista entre si, ou achar que a Revolução Francesa deu direitos a todos. É uma revolução burguesa: proclama a igualdade e a limita por sexo, renda e cor.",
 fogo:"Que ideias do Iluminismo aparecem na Constituição brasileira de 1988? Cite duas e diga de quem são."},

{area:"gh",tier:"cauda",topico:"Processos de independência no Continente Americano",freq:"não caiu como tema próprio em 2023.2–2026.2; o Haiti liga com o bloco de resistência escrava, o mais cobrado",
 saber:["Haiti (São Domingos): revolta de escravizados em 1791, independência em 1804 — <b>única revolução de escravizados vitoriosa</b> das Américas. Toussaint Louverture, Dessalines. Era a colônia mais lucrativa do mundo (açúcar e café).",
  "“Haitianismo”: o medo de um novo Haiti fez as elites escravistas, inclusive as do Brasil, endurecerem a repressão.",
  "América espanhola: liderança <b>criolla</b> (descendentes de espanhóis nascidos na América). Gatilho: invasão napoleônica da Espanha (1808). Bolívar no norte, San Martín no sul.",
  "Resultado: <b>fragmentação</b> em várias repúblicas (Bolívar, na Carta da Jamaica de 1815, já via a união como impossível); manutenção do latifúndio e da exclusão de indígenas.",
  "Brasil (1822): vinda da Corte em 1808 → independência como <b>monarquia</b>, com D. Pedro, mantendo unidade territorial, latifúndio e escravidão. Teve guerra: Bahia (2 de julho de 1823), Pará, Maranhão, Cisplatina."],
 armadilha:"Dizer que a independência do Brasil foi pacífica, ou que as independências fizeram revolução social. Em toda a América, mudou quem governava, não a estrutura de terra e de trabalho.",
 fogo:"Por que a América espanhola virou vários países e a portuguesa continuou um só?"},

{area:"gh",tier:"orbita",topico:"Revolução Industrial",freq:"não apareceu isolada nas provas de 2025.1 a 2026.2, mas está no edital e sustenta as questões de trabalho e tecnologia (IA em 2026.2)",
 saber:["Pioneirismo inglês: <b>cercamentos</b> (camponeses sem terra viram mão de obra urbana), capital do comércio colonial e do tráfico, carvão e ferro, e uma monarquia <b>parlamentar</b> desde 1688 — não absolutista.",
  "1ª Revolução (c. 1760–1850): tecelagem mecânica e máquina a vapor (aperfeiçoada por James Watt), fábrica, jornada de 14 a 16 horas, trabalho infantil, bairros operários sem saneamento.",
  "Reação operária: <b>ludismo</b> quebra máquinas (c. 1811–1816); <b>cartismo</b> pede ao Parlamento sufrágio universal masculino (Carta do Povo, 1838); <b>sindicatos</b> (trade unions) negociam salário e jornada.",
  "2ª Revolução (a partir de c. 1870): eletricidade, petróleo, aço, química; EUA e Alemanha disputam a liderança. <b>Taylorismo</b> cronometra tarefas; <b>fordismo</b> põe a linha de montagem (1913) e a produção em massa.",
  "3ª (informática, robótica) e 4ª (automação, IA, plataformas) — a ponte para as questões sobre uberização e IA."],
 armadilha:"Trocar ludismo por cartismo (um quebra máquina, o outro pede voto) e achar que a linha de montagem deu mais autonomia ao operário — ela fez o contrário.",
 fogo:"Por que tirar a terra dos camponeses ingleses ajudou a criar a fábrica?"},

{area:"gh",tier:"cauda",topico:"Imperialismo europeu na África e na Ásia",freq:"raro como tema central; aparece como pano de fundo de questões sobre África, desigualdade e recursos",
 saber:["Imperialismo (neocolonialismo do séc. XIX): potências industriais buscam <b>matérias-primas, mercados e áreas de investimento</b>.",
  "Justificativas: <b>darwinismo social</b> e a “missão civilizadora” — o “fardo do Homem Branco” (Kipling, 1899).",
  "<b>Conferência de Berlim</b> (1884–1885, convocada por Bismarck): regra da ocupação efetiva, Congo como domínio pessoal de Leopoldo II, nenhum africano presente. Fronteiras traçadas por interesse europeu, cortando povos.",
  "Em 1914, só <b>Etiópia</b> (vitória sobre a Itália em <b>Adwa, 1896</b>) e <b>Libéria</b> eram independentes.",
  "Ásia: <b>Guerras do Ópio</b> (1839–1842 e 1856–1860) → Tratado de Nanquim (1842) cede Hong Kong; China repartida em zonas de influência. Índia: Revolta dos Sipaios (1857) → domínio direto da Coroa britânica (1858)."],
 armadilha:"Dizer que as fronteiras africanas respeitaram etnias — é exatamente o contrário, e é a raiz de muitos conflitos atuais.",
 fogo:"Como o “fardo do Homem Branco” transformava exploração em suposta generosidade?"},

{area:"gh",tier:"orbita",topico:"Primeira Guerra Mundial e período entreguerras",freq:"pano de fundo frequente: a questão de nazismo de 2026.1 parte dele",
 saber:["Causas (a pólvora): imperialismo, nacionalismos (revanchismo francês pela Alsácia-Lorena, pan-eslavismo), corrida armamentista e alianças: <b>Tríplice Entente</b> (Reino Unido, França, Rússia) × <b>Tríplice Aliança</b> (Alemanha, Áustria-Hungria, Itália — que trocou de lado em 1915).",
  "Estopim: assassinato do arquiduque Francisco Ferdinando em <b>Sarajevo</b>, 28/06/1914. Guerra de trincheiras. EUA entram em 1917; Rússia sai em 1918, após a Revolução de 1917.",
  "<b>Tratado de Versalhes</b> (1919): culpa alemã (art. 231), reparações, exército de 100 mil homens, perda de colônias e da Alsácia-Lorena. Cria a <b>Liga das Nações</b> — sem os EUA.",
  "<b>Crise de 1929</b>: superprodução + especulação → quebra da Bolsa de Nova York, desemprego em massa. No Brasil, derruba o café e abre caminho para 1930.",
  "<b>New Deal</b> (Roosevelt, 1933): Estado intervém — obras públicas, previdência, regulação bancária (lógica de Keynes). Crise + ressentimento de Versalhes = terreno do nazifascismo."],
 armadilha:"Dizer que Versalhes criou a ONU (foi a Liga das Nações) ou que o New Deal reduziu o Estado (ele ampliou).",
 fogo:"Por que Sarajevo foi o estopim e não a causa da guerra?"},

{area:"gh",tier:"nucleo",topico:"Totalitarismos e Segunda Guerra Mundial",freq:"nazismo caiu em 2026.1; o tema volta com frequência",
 saber:["<b>Totalitarismo</b> (Hannah Arendt): partido único, ideologia oficial, propaganda, polícia política, terror e campos — quer controlar a pessoa inteira. <b>Autoritarismo</b> só cala a oposição.",
  "<b>Fascismo italiano</b>: Marcha sobre Roma (1922), Mussolini nomeado pelo rei; “Tudo no Estado, nada fora do Estado, nada contra o Estado”; corporativismo, ultranacionalismo, anticomunismo.",
  "<b>Stalinismo</b>: Planos Quinquenais (1928), coletivização forçada, Grandes Expurgos, gulags, culto ao líder. Ideologia oposta ao nazismo, mesma máquina de controle.",
  "<b>Holocausto</b> em escada: boicotes (1933) → Leis de Nuremberg (1935) → Noite dos Cristais (1938) → Wannsee e “Solução Final” (1942). ~6 milhões de judeus; também roma, deficientes, homossexuais.",
  "Cronologia: Polônia 1º/09/1939 → Pearl Harbor 7/12/1941 → Stalingrado 1942–43 → Dia D 6/06/1944 → rendição alemã 8/05/1945 → Hiroshima e Nagasaki (6 e 9/08/1945) → ONU (Carta de junho de 1945).",
  "Brasil: guerra ao Eixo em 1942; <b>FEB na Itália</b> (Monte Castello, fev. 1945). Contradição: o Estado Novo, ditadura, combatia o fascismo — Vargas cai em 1945."],
 armadilha:"Chamar o nazismo de esquerda por causa do nome “socialista”, ou dizer que a FEB lutou no Pacífico.",
 fogo:"O que nazismo e stalinismo têm em comum se as ideologias eram opostas?"},

{area:"gh",tier:"cauda",topico:"Guerra Fria: Cuba, crise dos mísseis e fim da URSS",freq:"complemento do tópico Guerra Fria; raro em detalhe",
 saber:["<b>Revolução Cubana</b> (1º/01/1959): Fidel Castro e Che Guevara derrubam o ditador Batista, aliado dos EUA. Baía dos Porcos (1961): invasão fracassada patrocinada pelos EUA.",
  "<b>Crise dos Mísseis</b> (out. 1962, 13 dias): mísseis soviéticos em Cuba → bloqueio naval de Kennedy → URSS retira os mísseis; EUA prometem não invadir Cuba (e tiram mísseis da Turquia). Depois, a “linha direta”.",
  "Muro de Berlim: erguido em 1961, aberto em <b>9/11/1989</b>. Alemanha reunificada em 1990; <b>URSS dissolvida em dezembro de 1991</b>.",
  "Gorbachev (1985): <b>glasnost</b> = transparência política; <b>perestroika</b> = reestruturação econômica. Queriam reformar o socialismo e aceleraram o fim."],
 armadilha:"Comprimir as datas: muro 89, Alemanha 90, URSS 91 — um ano de cada vez.",
 fogo:"Por que a Crise dos Mísseis é o momento em que a Guerra Fria quase deixou de ser “fria”?"},

{area:"gh",tier:"orbita",topico:"Independências na África e na Ásia",freq:"não apareceu isolada de 2025.1 a 2026.2; liga-se ao bloco de racismo e direitos humanos, que cai sempre",
 saber:["Contexto: potências europeias enfraquecidas após 1945, ONU defendendo autodeterminação, superpotências disputando os novos países.",
  "<b>Índia</b> (15/08/1947): Gandhi, satyagraha (resistência sem violência), Marcha do Sal (1930). Partição Índia × Paquistão com violência e migrações em massa.",
  "<b>Argélia</b>: guerra contra a França (1954–1962), liderada pela FLN. <b>Angola e Moçambique</b> (1975): guerras desde 1961 + Revolução dos Cravos (25/04/1974) em Portugal. Angola cai em guerra civil disputada na Guerra Fria.",
  "<b>Conferência de Bandung</b> (1955, Indonésia): países afro-asiáticos, origem do Movimento dos Não Alinhados (1961) e da ideia de Terceiro Mundo.",
  "<b>Apartheid</b> (1948–início dos anos 1990): segregação legal na África do Sul. Sharpeville (1960), Soweto (1976). Mandela preso 1964–1990, presidente em 1994."],
 armadilha:"Dizer que as independências portuguesas foram pacíficas, ou que o apartheid vem do século XVII — como lei, é de 1948.",
 fogo:"Que ligação existe entre as guerras em Angola e Moçambique e o fim da ditadura em Portugal?"},

{area:"gh",tier:"orbita",topico:"Imperialismos dos séculos XX e XXI e resistências",freq:"terras raras e geopolítica caíram em 2026.2; o tema tende a voltar via notícia atual",
 saber:["<b>Neocolonialismo</b> (Nkrumah, 1965): país formalmente independente, mas com economia e política dirigidas de fora — dívida, exportação de matéria-prima barata, empresas estrangeiras.",
  "<b>Vietnã</b>: França derrotada em Dien Bien Phu (1954) → país dividido → intervenção dos EUA (teoria do dominó) → retirada em 1973 → queda de Saigon (1975). Enormes protestos nos EUA.",
  "<b>América Latina</b>: golpe na Guatemala (1954, Árbenz, United Fruit, CIA); golpe no Chile (11/09/1973, Allende — eleito — deposto por Pinochet); <b>Operação Condor</b> (anos 1970) unindo a repressão do Cone Sul, Brasil incluso.",
  "Século XXI: expansão da OTAN para o leste; anexação da Crimeia (2014) e invasão da Ucrânia (24/02/2022), condenada na Assembleia Geral da ONU; disputa por recursos estratégicos como petróleo e <b>terras raras</b>.",
  "Na prova, separar <b>fato</b> (quem fez o quê, quando) de <b>argumento</b> de cada lado."],
 armadilha:"Dizer que Allende chegou ao poder por revolução armada (foi eleito) ou que a Ucrânia era membro da OTAN em 2022 (não era).",
 fogo:"Por que um país que só exporta matéria-prima continua dependente mesmo sendo independente?"},

{area:"gh",tier:"nucleo",topico:"Contracultura, direitos civis e direitos humanos",freq:"direitos humanos caiu em 2025.1; gênero e racismo caem em toda prova",
 saber:["<b>Contracultura</b> (anos 1960): jovens contra consumismo, moral tradicional e Guerra do Vietnã. Hippies, “paz e amor”, Woodstock (1969), Maio de 68 na França (estudantes + greve geral).",
  "No Brasil: <b>Tropicália</b> (Caetano, Gil, Tom Zé, Os Mutantes), “É proibido proibir” (1968); Caetano e Gil presos após o AI-5 e exilados.",
  "<b>Direitos civis nos EUA</b>: leis Jim Crow mantinham a segregação após a abolição (1865). Rosa Parks (1955) e o boicote de Montgomery; Martin Luther King (não violência, “Eu tenho um sonho”, 1963); Malcolm X (autodefesa, orgulho negro). Lei dos Direitos Civis (1964) e do Voto (1965).",
  "<b>DUDH</b> (10/12/1948, ONU): resposta ao Holocausto e à guerra. <b>Universal</b> (vale para toda pessoa, sem distinção) e <b>indivisível</b> (direitos civis, políticos e sociais juntos). Raiz na Declaração de 1789.",
  "Lei Maria da Penha (2006) prevê vários tipos de violência contra a mulher (física, psicológica, sexual, patrimonial, moral) — caiu em 2026.2."],
 armadilha:"Dizer que direitos humanos valem para grupos específicos ou só para cidadãos de alguns países — o que cai é a UNIVERSALIDADE.",
 fogo:"Por que a abolição de 1865 nos EUA não acabou com a segregação?"},

/* ===================== LÍNGUA PORTUGUESA ===================== */
{area:"port",tier:"nucleo",topico:"Interpretação: ideia central, inferência e informação explícita",freq:"presente em praticamente todas as 7 questões",
 saber:["Separar o que o texto <b>diz</b> (explícito), o que ele <b>deixa concluir</b> (inferência) e o que <b>você acha</b> (fora do texto — sempre errado na prova).",
  "Localizar a tese: normalmente no primeiro ou no último parágrafo; o meio traz argumento e exemplo.",
  "Toda alternativa tem que ser sustentada por um trecho. Se você não consegue apontar a linha, não é ela.",
  "Cuidado com extrapolação: alternativa verdadeira no mundo, mas não afirmada no texto.",
  "Palavras absolutas ('sempre', 'nunca', 'todos', 'apenas') costumam derrubar a alternativa — o texto raramente é tão categórico."],
 armadilha:"Responder pelo que você sabe do assunto em vez do que o autor escreveu. Em prova de interpretação, o texto é a única autoridade.",
 fogo:"Qual a diferença entre uma inferência válida e uma extrapolação?"},

{area:"port",tier:"nucleo",topico:"Análise de afirmativas I / II / III",freq:"formato recorrente — e não só em Português",
 saber:["Julgar cada afirmativa <b>isoladamente</b>, marcando V ou F ao lado dela, antes de olhar as alternativas.",
  "Depois eliminar toda alternativa que contrarie um julgamento de que você tem certeza. Duas certezas costumam matar a questão.",
  "Uma afirmativa só é verdadeira se for verdadeira <b>inteira</b>. Meia frase certa e meia errada = falsa.",
  "Atenção aos operadores: 'apenas I e II', 'todas', 'nenhuma'. Ler o conector da alternativa com o mesmo cuidado que a afirmativa."],
 armadilha:"Ler as alternativas antes de julgar as afirmativas — isso contamina o julgamento. Julgue primeiro, olhe depois.",
 fogo:"Descreva seu procedimento, passo a passo, para uma questão I/II/III."},

{area:"port",tier:"nucleo",topico:"Gêneros textuais e efeito de sentido",freq:"o suporte da maioria das questões",
 saber:["Reconhecer gênero pelo propósito: tirinha e charge (humor/crítica), notícia (informar), reportagem (aprofundar), artigo de opinião (convencer), manual e receita (instruir), anúncio (persuadir), poema (expressar).",
  "Charge e tirinha: o sentido está na <b>quebra de expectativa</b> do último quadro, e geralmente critica algo do mundo real.",
  "Linguagem verbal × não verbal: em tirinha, imagem, traço e balão fazem parte do argumento.",
  "Anúncio publicitário: verbo no imperativo, 2ª pessoa, trocadilho, apelo emocional.",
  "Tipologias dentro dos gêneros: narração, descrição, dissertação/argumentação, exposição, injunção."],
 armadilha:"Explicar a piada da tirinha sem apontar a crítica social por trás. A alternativa certa quase sempre nomeia essa crítica.",
 fogo:"Pegue uma tirinha e explique onde exatamente está a quebra de expectativa."},

{area:"port",tier:"nucleo",topico:"Coesão, conectivos e referenciação",freq:"~1 por prova",
 saber:["Sentido dos conectivos — é isso que a prova cobra: <b>mas/porém/contudo/entretanto</b> = oposição; <b>portanto/logo/assim</b> = conclusão; <b>porque/pois/já que</b> = causa; <b>embora/apesar de/ainda que</b> = concessão; <b>se</b> = condição; <b>para que</b> = finalidade.",
  "Substituir um conectivo por outro só mantém o sentido se for do mesmo grupo — é a pegadinha mais comum do tema.",
  "Coesão referencial: pronomes (ele, isso, aquilo), sinônimos e elipse evitam repetição. A prova pergunta 'a que se refere a palavra X na linha Y'.",
  "Coerência é sentido global: contradição interna quebra a coerência mesmo com a gramática perfeita."],
 armadilha:"Trocar 'mas' por 'portanto' e achar que o sentido se mantém. Um opõe, o outro conclui.",
 fogo:"'Estudou muito, mas não passou' e 'Estudou muito, portanto não passou' — o que muda?"},

{area:"port",tier:"nucleo",topico:"Variação linguística e preconceito linguístico",freq:"item explícito do Anexo V, cai com frequência",
 saber:["Variação regional (sotaque, léxico), social, etária, de registro (formal × informal) e histórica.",
  "Não existe variedade 'errada': existe <b>adequação ao contexto</b>. A norma-padrão é uma variedade de prestígio, não a única correta.",
  "Preconceito linguístico é preconceito social disfarçado de correção gramatical.",
  "Gírias, internetês e regionalismos são legítimos no contexto deles.",
  "A prova costuma trazer um texto com fala popular e perguntar sobre adequação — a resposta valoriza a variedade, nunca a ridiculariza."],
 armadilha:"Marcar a alternativa que chama a fala popular de 'erro' ou de 'português mal falado'. Essa nunca é a resposta.",
 fogo:"Por que 'nós vai' não é falta de inteligência, e sim variação?"},

{area:"port",tier:"orbita",topico:"Denotação, conotação e figuras de linguagem",freq:"~1 por prova",
 saber:["Denotativo = literal (dicionário). Conotativo = figurado (poesia, publicidade, humor).",
  "Metáfora (comparação implícita: 'ele é uma fera') × comparação (com 'como').",
  "Metonímia: parte pelo todo ('beber um copo'). Personificação: dar traço humano ao inanimado.",
  "Ironia: dizer o contrário do que se quer — é a figura que mais cai em charge e crônica.",
  "Hipérbole (exagero), eufemismo (suavizar), antítese (opostos), ambiguidade (duplo sentido, às vezes proposital na publicidade)."],
 armadilha:"Chamar de metáfora o que é ironia. Se o texto diz o contrário do que quer transmitir, é ironia.",
 fogo:"Dê um exemplo de ironia que você usou hoje e explique o mecanismo."},

{area:"port",tier:"orbita",topico:"Classes de palavras e sintaxe em contexto",freq:"embutida numa questão de análise, quase nunca isolada",
 saber:["Reconhecer em uso: substantivo, adjetivo (caracteriza), verbo, advérbio (modifica verbo/adjetivo: modo, tempo, lugar, intensidade), pronome, conjunção, preposição.",
  "Sujeito e predicado; sujeito oculto, indeterminado e oração sem sujeito ('há', 'faz' de tempo, fenômeno da natureza).",
  "Vocativo (chama o interlocutor, sempre entre vírgulas) × aposto (explica um termo anterior).",
  "Transitividade: verbo transitivo direto, indireto e intransitivo — necessária para regência e crase.",
  "Concordância verbal e nominal; voz ativa × passiva ('o menino comeu o bolo' → 'o bolo foi comido pelo menino')."],
 armadilha:"Questão que pede 'a função da palavra X no texto' e você responde a classe. Classe é o que a palavra é; função é o que ela faz na frase.",
 fogo:"Na frase 'Maria, traga o livro rapidamente', aponte vocativo, verbo e advérbio."},

{area:"port",tier:"orbita",topico:"Pontuação e efeito de sentido",freq:"~1 a cada duas provas",
 saber:["Vírgula separa termos em série, isola vocativo, aposto e adjunto deslocado, e marca oração intercalada.",
  "Vírgula muda sentido: 'Não, espere' × 'Não espere'. A prova adora esse contraste.",
  "Dois-pontos anunciam explicação, enumeração ou fala. Ponto e vírgula separa itens longos ou orações relacionadas.",
  "Reticências sugerem suspensão; travessão marca fala ou intercala com ênfase; aspas indicam citação, ironia ou uso especial da palavra.",
  "Ponto de exclamação e interrogação alteram a intenção do enunciado."],
 armadilha:"Colocar vírgula entre sujeito e verbo. Nunca se separa sujeito do verbo por vírgula.",
 fogo:"Explique como uma vírgula pode inverter o sentido de uma frase, com exemplo."},

{area:"port",tier:"cauda",topico:"Crase, regência, acentuação e ortografia",freq:"raro isolado — sempre embutido",
 saber:["Crase = a (preposição) + a (artigo). Testa trocando por palavra masculina: 'vou à feira' → 'vou ao mercado' → tem crase.",
  "Nunca antes de palavra masculina, verbo ou pronome pessoal. Sempre em 'à medida que', 'às vezes', 'à noite'.",
  "Regência: assistir ao filme, obedecer a alguém, preferir A a B (sem 'do que'), namorar alguém (sem 'com').",
  "Acentuação: proparoxítona sempre acentuada; oxítona em a/e/o; hiato i/u tônicos isolados.",
  "Mau (adjetivo, oposto de bom) × mal (advérbio, oposto de bem); mas × mais; onde (lugar) × aonde (com movimento)."],
 armadilha:"Este bloco dá a ilusão de que 'estudar português' é isso. Não é — vale menos de uma questão. Interpretação vale seis.",
 fogo:"'Vou à escola' e 'vou a pé': por que uma tem crase e a outra não?"},

{area:"port",tier:"cauda",topico:"Período composto e orações subordinadas",freq:"raro",
 saber:["Coordenação: orações independentes (aditiva, adversativa, alternativa, conclusiva, explicativa).",
  "Subordinação: uma oração depende da outra — substantivas (funcionam como sujeito/objeto), adjetivas (qualificam, começam com pronome relativo) e adverbiais (causa, tempo, condição, concessão, finalidade).",
  "Adjetiva <b>restritiva</b> (sem vírgula, restringe) × <b>explicativa</b> (entre vírgulas, comenta). 'Os alunos que estudaram passaram' ≠ 'Os alunos, que estudaram, passaram'.",
  "Na prática, o que cai é o <b>sentido</b> da relação, não o nome dela."],
 armadilha:"Decorar nomenclatura. A prova pergunta o sentido ('a segunda oração indica…'), não a etiqueta.",
 fogo:"Qual a diferença de sentido entre a oração adjetiva com e sem vírgula?"}

];
